box::use(
  utils[...],
  RMariaDB[...]
)


# Ask database for the usernames and passwords for the tool
userQuery <- function(){
  # Establish the connection to the projects database
  usersDb <- dbConnect(RMariaDB::MariaDB(), user='sepia', password="sepia_TRR241", dbname='Users', host='localhost')
  
  # Create the query with the project name
  queryUserText <- "select * from SepiaUsers;"
  
  # Run the query against the database and fetch the resulting dataframe
  rsUserInsert <- dbSendQuery(usersDb, queryUserText)
  dbUserRows <- dbFetch(rsUserInsert)
  
  # Clear the query
  dbClearResult(rsUserInsert)
  
  # Disconnect the database
  dbDisconnect(usersDb)
  
  # return projects dataframe
  return(dbUserRows)
}

#Temporal table for usernames and passwords
#' @export
userBase <- userQuery()

# Generate lists of options for the displays
#' @export
fullExp <- list(
  "DSSTC" = "DSS_TimeCourse",
  "WH" = "WoundHealing"
)

#' @export
singleExp <- list(
  "AcDSS" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_DSS_Cerl"),
  "cDSS" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_cDSS_Cerl"),
  # "DSSTCim" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Inf_mid_Healthy"),
  # "DSSTCih" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Inf_hi_Healthy"),
  # "DSSTCrm" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Rec_mod_Healthy"),
  # "DSSTCrf" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Rec_ful_Healthy"),
  # "OxC_old" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_OxC_Cerl"),
  "C8KOc" = list("project" = "Casp8Colon", "tabid" = "Casp8Colon_Col_Casp8dIEC_Col_Casp8flox"),
  "C8KOi" = list("project" = "Casp8Ileum", "tabid" = "Casp8Ileum_D4_Casp8dIEC_D4_Casp8flox"),
  "Opa1KO" = list("project" = "Opa1_KO", "tabid" = "Opa1_KO_KO_WT"),
  "OxC" = list("project" = "OxaCitro", "tabid" = "OxaCitro_OxC_Healthy"),
  "TC" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_TC_RKO"),
  "TdAc" = list("project" = "TNFdARE_model", "tabid" = "TNFdARE_model_Col_dARE_Col_WT"),
  "TdAi" = list("project" = "TNFdARE_model", "tabid" = "TNFdARE_model_SI_dARE_SI_WT"),
  "AcTNBS" = list("project" = "TNBS_model", "tabid" = "TNBS_model_TNBS_Ac_Healthy"),
  "cTNBS" = list("project" = "TNBS_model", "tabid" = "TNBS_model_TNBS_Chr_Healthy"),
  "AntiCD36h" = list("project" = "AntiCd3", "tabid" = "AntiCd3_C6h_O0h"),
  "AntiCD324h" = list("project" = "AntiCd3", "tabid" = "AntiCd3_C24h_O0h"),
  # "AOMDSS_e" = list("project" = "AOMDSS", "tabid" = "AOMDSS_AcDSS_Healthy"),
  # "AOMDSS_l" = list("project" = "AOMDSS", "tabid" = "AOMDSS_chrDSS_Healthy"),
  # "AOMDSS_t" = list("project" = "AOMDSS", "tabid" = "AOMDSS_AOMDSS_Healthy"),
  # "WH6" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h6_h0"),
  # "WH24" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h24_h0"),
  # "WH48" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h48_h0"),
  "EvInf" = list("project" = "Eimeria_vermiformis_model", "tabid" = "Eimeria_vermiformis_model_EV_WT"),
  "HhInf" = list("project" = "HhColitis", "tabid" = "HhColitis_HhCol_SSt"),
  "CB" = list("project" = "OxaCitro", "tabid" = "OxaCitro_CB_Healthy")
)

#' @export
displayNames <- list("Acute DSS (2%)" = "AcDSS",
                    #  "Acute DSS (1.5%)" = "AOMDSS_e",
                     "Chronic DSS (2%)" = "cDSS",
                    #  "Chronic DSS (1%)" = "AOMDSS_l",
                    #  "AOM DSS" = "AOMDSS_t",
                    #  "DSS Time course - Mid inflammation (DSS 3%, day 3)" = "DSSTCim",
                    #  "DSS Time course - High inflammation (DSS 3%, day 8)" = "DSSTCih",
                    #  "DSS Time course - Moderate recovery (after DSS, day 12)" = "DSSTCrm",
                    #  "DSS Time course - Full recovery (after DSS, day 19)" = "DSSTCrf",
                    #  "Oxazolone colitis - Old version" = "OxC_old",
                     "Casp8ΔIEC colitis" = "C8KOc",
                     "Casp8ΔIEC ileitis" = "C8KOi",
                     "Opa1ΔIEC colitis" = "Opa1KO",
                     "Oxazolone colitis" = "OxC",
                     "T cell transfer colitis" = "TC",
                     "TNFΔARE colitis" = "TdAc",
                     "TNFΔARE ileitis" = "TdAi",
                     "Acute TNBS colitis" = "AcTNBS",
                     "Chronic TNBS colitis" = "cTNBS",
                     "Anti-CD3 enteritis (6h)" = "AntiCD36h",
                     "Anti-CD3 enteritis (24h)" = "AntiCD324h",
                    #  "Wound Healing time course - h6" = "WH6",
                    #  "Wound Healing time course - h24" = "WH24",
                    #  "Wound Healing time course - h48" = "WH48",
                     "Eimeria vermiformis infection" = "EvInf",
                     "Helicobacter colitis infection" = "HhInf",
                     "Citrobacter rodentium infection" = "CB"
                     )

#' @export
displayNames_sort <- list("AcDSS" = "AcDSS",
                    #  "Acute DSS (1.5%)" = "AOMDSS_e",
                     "cDSS" = "cDSS",
                    #  "Chronic DSS (1%)" = "AOMDSS_l",
                    #  "AOM DSS" = "AOMDSS_t",
                    #  "DSS Time course - Mid inflammation (DSS 3%, day 3)" = "DSSTCim",
                    #  "DSS Time course - High inflammation (DSS 3%, day 8)" = "DSSTCih",
                    #  "DSS Time course - Moderate recovery (after DSS, day 12)" = "DSSTCrm",
                    #  "DSS Time course - Full recovery (after DSS, day 19)" = "DSSTCrf",
                    #  "Oxazolone colitis - Old version" = "OxC_old",
                     "Casp8ΔIECCol" = "C8KOc",
                     "Casp8ΔIECIle" = "C8KOi",
                     "Opa1ΔIEC" = "Opa1KO",
                     "OxaC" = "OxC",
                     "TC" = "TC",
                     "TnfΔARECol" = "TdAc",
                     "TnfΔAREIle" = "TdAi",
                     "AcTNBS" = "AcTNBS",
                     "cTNBS" = "cTNBS",
                     "AntiCD3_6h" = "AntiCD36h",
                     "AntiCD3_24h" = "AntiCD324h",
                    #  "Wound Healing time course - h6" = "WH6",
                    #  "Wound Healing time course - h24" = "WH24",
                    #  "Wound Healing time course - h48" = "WH48",
                     "Everm" = "EvInf",
                     "Hhepa" = "HhInf",
                     "Crode" = "CB"
                     )

#' @export
imgFormat <- list("PNG" = ".png",
                  "JPEG" = ".jpeg",
                  "PDF" = ".pdf",
                  "SVG" = ".svg"
)

#' @export
modelDescriptions <- list(
  "AcDSS" = "Dextran Sulfate Sodium (<b>DSS</b>) is a sulphated polysaccharide that is administered to the mouse via drinking water (<a href=\"https://doi.org/10.3748/WJG.V23.I33.6016\">Eichele and Kharbanda, 2017</a>). A few days after the start of the treatment, the mice show symptoms of severe colitis, with characteristic indicators such as weight loss, diarrhoea, ulcers and breakdown of the intestinal barrier (<a href=\"https://doi.org/10.3791/3678\">Kim <i>et. al.</i>, 2012</a>)⁠. Using endoscopy, it is possible to observe inflammatory patches in the intestinal epithelium. At the cellular level, loss of the crypt architecture can be observed as a result of the extensive tissue damage to the intestinal epithelium⁠ (<a href=\"https://doi.org/10.1002/0471142735.IM1525S104\">Chassaing <i>et. al.</i>, 2014</a>). This damage causes an infiltration of the mucosal microbiota, triggering an immune response. All of these features are similar to those observed in flares of human UC. </br></br>For acute colitis, mice are administered 2% DSS in drinking water for 8 days, afer which they are sacrificed and their tissues extracted for sequencing, as described in established protocols (<a href=\"https://doi.org/10.1038/nprot.2017.044\">Wirtz <i>et. al.</i>, 2017</a>). Intestinal inflammation and other symptoms of colitis are regularly monitored.",
  "cDSS" = "Dextran Sulfate Sodium (<b>DSS</b>) is a sulphated polysaccharide that is administered to the mouse via drinking water (<a href=\"https://doi.org/10.3748/WJG.V23.I33.6016\">Eichele and Kharbanda, 2017</a>). A few days after the start of the treatment, the mice show symptoms of severe colitis, with characteristic indicators such as weight loss, diarrhoea, ulcers and breakdown of the intestinal barrier (<a href=\"https://doi.org/10.3791/3678\">Kim <i>et. al.</i>, 2012</a>)⁠. Using endoscopy, it is possible to observe inflammatory patches in the intestinal epithelium. At the cellular level, loss of the crypt architecture can be observed as a result of the extensive tissue damage to the intestinal epithelium⁠ (<a href=\"https://doi.org/10.1002/0471142735.IM1525S104\">Chassaing <i>et. al.</i>, 2014</a>). This damage causes an infiltration of the mucosal microbiota, triggering an immune response. All of these features are similar to those observed in flares of human UC. </br></br>For chronic colitis, mice are administered 1.5% DSS in drinking water for 8 days, point at which the treatment is interrupted and the mice are left to recover. The DSS cycles are administered two more times and the mice are then sacrificed and their tissues extracted for sequencing, as described in established protocols (<a href=\"https://doi.org/10.1038/nprot.2017.044\">Wirtz <i>et. al.</i>, 2017</a>).",
  "C8KOc" = "<b>Caspase 8</b> plays an important role in the regulation and control of cellular apoptosis, and is a key element in the process of epithelial turnover and maintenance. Mice with the gene for Casp8 gene knocked out in intestinal epithelium cells develop ileitis after 8-10 weeks, with some cases also developing a form of colitis. There is a loss of Paneth cells and other secretory types in the tissue, resulting in a lack of mucosal secretion⁠ (<a href=\"https://doi.org/10.1136/GUTJNL-2014-307226\">Guenther, <i>et. al.</i>, 2015</a>). As the apoptotic pathway is largely blocked, the epithelial cells appear to die instead by necroptosis, mediated by the Ripk3 kinase⁠, which is much less favourable for the turnover systems of the intestinal epithelium. Inhibition or knock-out of Ripk3 in other models, together with the inactivation of Casp8, prevents the necroptotic cascade. The loss of secretory cells and the cumulative dysfunction of the intestinal turnover put the epithelial barrier at risk, making the mice much more susceptible to infection. Overall, the symptoms experienced by the mice are more similar to those observed with human CD (<a href=\"https://doi.org/10.1038/s41586-019-1770-6\">Fritsch, <i>et. al.</i>, 2019</a>).",
  "C8KOi" = "<b>Caspase 8</b> plays an important role in the regulation and control of cellular apoptosis, and is a key element in the process of epithelial turnover and maintenance. Mice with the gene for Casp8 gene knocked out in intestinal epithelium cells develop ileitis after 8-10 weeks, with some cases also developing a form of colitis. There is a loss of Paneth cells and other secretory types in the tissue, resulting in a lack of mucosal secretion⁠ (<a href=\"https://doi.org/10.1136/GUTJNL-2014-307226\">Guenther, <i>et. al.</i>, 2015</a>). As the apoptotic pathway is largely blocked, the epithelial cells appear to die instead by necroptosis, mediated by the Ripk3 kinase⁠, which is much less favourable for the turnover systems of the intestinal epithelium. Inhibition or knock-out of Ripk3 in other models, together with the inactivation of Casp8, prevents the necroptotic cascade. The loss of secretory cells and the cumulative dysfunction of the intestinal turnover put the epithelial barrier at risk, making the mice much more susceptible to infection. Overall, the symptoms experienced by the mice are more similar to those observed with human CD (<a href=\"https://doi.org/10.1038/s41586-019-1770-6\">Fritsch, <i>et. al.</i>, 2019</a>).",  
  "OxC" = "The haptenizing agent <b>oxazolone</b> causes severe colitis after intrarectal administration in mice (<a href=\"https://doi.org/10.1084/JEM.188.10.1929\">Boirivant <i>et. al.</i>, 1998</a>). The mice suffer of inflammation of the distal mucosa and submucosa, and experience ulcerations in the epithelium. Multiple immune cells, such as Nk cells, macrophages, neutrophils and lymphocytes can be found infiltrating the lamina propria (<a href=\"https://doi.org/10.1016/S1074-7613(02)00453-3\">Heller <i>et. al.</i>, 2002</a>). Multiple strains of mice can be used to run this model, some of them being more susceptible than others. Strains SJL/L or C57BL/10 have more sensibility to the treatment, but other strains, such as C57BL/6 might need some form of subcutaneous sensibilization beforehand <a href=\"https://doi.org/10.1038/nprot.2017.044\">Wirtz <i>et. al.</i>, 2017</a>.</br></br>Some of the histological features that are observed in the mice, such as inflammation of the distant colon, or an elevated production of cytokines are similar to the symptoms observed in ulcerative colitis in humans, so the model has been used to study such responses in the context of the disease.",
  "TC" = "Given the role of the immune response in the development of inflammatory bowel disease, the <b>adoptive transfer</b> model of colitis in mice is one of the best suited models to study CD4+ T cell induced inflammation (<a href=\"https://doi.org/10.1007/978-1-61779-527-5_19/COVER\">Eri <i>et. al.</i>, 2011</a>). The principle of this model is rooted in the capability of CD4+ CD45rbHigh T cells from spleen or lymph nodes to cause intestinal inflammatory disease in the gut. To obtain this effect, the cells are to be transfered into immune-defficient Rag1 KO mice, which lacks the lymphocyte lineage. The cells then react, secreting cytokines that trigger an inflammatory response in the gut epithelium. Symptoms begin appearing somewhere around 6-8 weeks.</br></br>The imbalance between effector T cells and regulatory T cells is a key condition for the development of inflammation in this model. Transfection of unsorted T cells or regulatory T cells exclusively fails to induce inflammation (<a href=\"https://doi.org/10.1093/INTIMM/5.11.1461\">Powrie <i>et. al.</i>, 1993</a>).",  
  "TdAc" = "Because of its role in the immune response, <b>TNFa</b> activity is highly regulated by several mechanisms and factors. One of these regulatory elements is the AU-rich element (ARE) regions of the 3’UTR region of the TNF gene, which act as repressors of the gene expression⁠ (<a href=\"https://doi.org/10.1016/S1074-7613(00)80038-2\">Kontoyiannis <i>et. al.</i>, 1999</a>). A mutation in these regions causes the production of a more stable version of the TNFa mRNA, resulting in increased production of TNFa. Mice born with this modification show symptoms similar to human CD⁠ (<a href=\"https://doi.org/10.1371/JOURNAL.PONE.0072594\">Bamias <i>et. al.</i>, 2013</a>), including mucosal abnormalities, and infiltration of immune cells into the epithelial tissue. The effect occurs mainly in the terminal ileum, but can occasionally extend to the colon. The immune response follows the pattern of a Th1-type, and the intestinal epithelial damage increases with the age of the mice (<a href=\"https://doi.org/10.1016/J.IJMM.2021.151489\">Ahmed <i>et. al.</i>p, 2021</a>).</br></br>Because the change occurs at a systemic level, this model is also used to the study the extraintestinal effects of IBD, and other inflammatory diseases such as rheumatoid arthritis.",
  "TdAi" = "Because of its role in the immune response, <b>TNFa</b> activity is highly regulated by several mechanisms and factors. One of these regulatory elements is the AU-rich element (ARE) regions of the 3’UTR region of the TNF gene, which act as repressors of the gene expression⁠ (<a href=\"https://doi.org/10.1016/S1074-7613(00)80038-2\">Kontoyiannis <i>et. al.</i>, 1999</a>). A mutation in these regions causes the production of a more stable version of the TNFa mRNA, resulting in increased production of TNFa. Mice born with this modification show symptoms similar to human CD⁠ (<a href=\"https://doi.org/10.1371/JOURNAL.PONE.0072594\">Bamias <i>et. al.</i>, 2013</a>), including mucosal abnormalities, and infiltration of immune cells into the epithelial tissue. The effect occurs mainly in the terminal ileum, but can occasionally extend to the colon. The immune response follows the pattern of a Th1-type, and the intestinal epithelial damage increases with the age of the mice (<a href=\"https://doi.org/10.1016/J.IJMM.2021.151489\">Ahmed <i>et. al.</i>p, 2021</a>).</br></br>Because the change occurs at a systemic level, this model is also used to the study the extraintestinal effects of IBD, and other inflammatory diseases such as rheumatoid arthritis.",
  "AcTNBS" = "For this model, the haptenating agent 2,4,6-trinitrobenzene sulphonic acid (<b>TNBS</b>) in administrated intrarectally toughether with ethanol in mice (<a href=\"https://pubmed.ncbi.nlm.nih.gov/8757344/\">Elson <i>et. al.</i>, 1996</a>). The ethanol impairs barrier function, and provides the tNBS access to the intestinal cells and penetrate the epithelium. This causes haptenization of some of the present proteins and triggers an immune response by CD4+ T cells (<a href=\"https://doi.org/10.1038/nprot.2017.044\">Wirtz <i>et. al.</i>, 2017</a>). This type of response makes the model a good candidate to study the CD4+ T cell responses in intestinal inflammation.  Although the rationale is similar to the oxazolone colitis model, the symptoms experienced by the mice resemble more human CD, rather than human UC.",
  "cTNBS" = "For this model, the haptenating agent 2,4,6-trinitrobenzene sulphonic acid (<b>TNBS</b>) in administrated intrarectally toughether with ethanol in mice (<a href=\"https://pubmed.ncbi.nlm.nih.gov/8757344/\">Elson <i>et. al.</i>, 1996</a>). The ethanol impairs barrier function, and provides the tNBS access to the intestinal cells and penetrate the epithelium. This causes haptenization of some of the present proteins and triggers an immune response by CD4+ T cells (<a href=\"https://doi.org/10.1038/nprot.2017.044\">Wirtz <i>et. al.</i>, 2017</a>). This type of response makes the model a good candidate to study the CD4+ T cell responses in intestinal inflammation.  Although the rationale is similar to the oxazolone colitis model, the symptoms experienced by the mice resemble more human CD, rather than human UC. </br></br>A chronic form of TNBS colitis can be induced by administration of a lower concentration of TNBS over multiple cycles. Over the treatment, the mouse develops lamina propria fibrosis, similar to the symptom present in some forms of IBD. Since the immune system adapts to the stimuli provided, the observed response varies slightly and is more intense with every cicle, allowing researchers to study the dinamism of the immune response (<a href=\"https://doi.org/10.3390/ijms23094739\">Silva <i>et. al.</i>, 2022</a>).",
  "EvInf" = "<i>Eimeria vermiformis</i> is an intracellular single cell protozoan pathogen, which specifically infects the small intestine epithelium. This pathogen is a natural self-limiting murine parasite that induces a strong non-lethal immune response and establishes a protective immunity in the host against future infections (<a href=\"https://doi.org/10.21769/BIOPROTOC.3122\">Figueiredo-Campos <i>et. al.</i>, 2018</a>). Its life cycle is also completed in a single step, without the need of a second host, so the model is ideal to study the host mechanisms of defense against an infection in the small intestinal epithelium. </br></br>The mice infected with this pathogen excrete a non-infectious, unsporulated form of oocysts that mature and become infectious after 2-7 days in a moist environment. Mice who ingest these matured oocysts are then infected with the pathogen and disseminate it further. After a dew days of infection, the epithelium begins to suffer damage, first to the epithelial cells, and then to the specialised epithelial cells, such as goblet cells (<a href=\"https://doi.org/10.1007/S00436-008-1256-1/FIGURES/7\">Linh <i>et. al.</i>, 2009</a>).",
  "HhInf" = "One of the drivers of the immune response is IL-10, a pro-inflammatory cytokine recognised by macrophages, among others. Blocking IL-10 signalling in mice produces animals that are more sensitive to develop inflammation, whether the block is temporary, through treatment with a blocker, or permanent, through genetic modification⁠ (<a href=\"https://doi.org/10.1016/0092-8674(93)80068-P\">Kuehn <i>et. al</i>, 1993</a>). One of the least sensitive mouse strain groups to this treatment/modification is the C57BL set, which does not develop spontaneous colitis when IL-10 signalling is blocked. Instead, these mouse strains need to be challenged with external stimuli, such as an infection (<a href=\"https://doi.org/10.1128/IAI.66.11.5157-5166.1998/ASSET/45817B2A-1135-490A-8A17-B2BBCB5101E6/ASSETS/GRAPHIC/II1180836008.JPEG\">Kullberg <i>et. al</i>, 1998</a>). </br></br> A number of bacteria from the Helicobacter genera have been associated with various types of gastric disease. <i>Helicobacter hepaticus</i> is used to challenge IL-10-deficient mice to develop intestinal inflammation. Infection with the bacteria alone does not cause intestinal inflammation as the mouse immune system protects against it, so a combination of the IL-10 signalling blockade and the infection is required for this model. The infection, combined with the blockade of IL-10 signalling produces a form of colitis in the animal. Infected mice show symptoms similar to human IBD, such as weight loss, rectal prolapse and colonic inflammation and lesions (<a href=\"https://doi.org/10.1038/mi.2010.61\">Fox <i>et. al</i>, 2010</a>).",
  "CB" = "In some intestinal diseases, Gram-negative bacteria play an important role as pathogens. An equivalentorganism to some of these pathogens in mice is <i>Citrobacter rodentium</i>, which shares the pathogenicity gene cassette with pathogenic strains of <i>E. coli</i>⁠ (<a href=\"https://doi.org/10.1128/JB.01144-09\">Petty <i>et. al</i>, 2010</a>). The attachment to the intestinal epithelium and action of the bacteria causes injury to the intestinal wall, triggering an inflammatory response, which in the case of <i>C. rodentium</i> is used to model processes in IBD⁠ (<a href=\"https://doi.org/10.1038/mi.2017.47\">Silberger <i>et. al</i>, 2017</a>). As a result of this inflammatory process, the diversity of some of the intestinal bacterial lineages is reduced, and several intestinal epithelial disorders develop, such as colonic hyperplasia, which is also seen in human IBD⁠. Infected mice develop colitis after 7 days, and are completely cleared from the faeces within 2-3 weeks after the initial infection (<a href=\"https://doi.org/10.1111/J.1462-5822.2004.00414.X\">Wiles <i>et. al</i>, 2004</a>).",
  "AntiCD36h" = "The anti-CD3 enteritis model (<b>AntiCD3</b>) is a murine model generated by the administration of a monoclonal <a href=\"https://www.bdbiosciences.com/en-eu/products/reagents/flow-cytometry-reagents/research-reagents/single-color-antibodies-ruo/purified-na-le-hamster-anti-mouse-cd3e.553057?tab=product_details\">anti CD3e antibody</a>. This antibody can activate either unprimed (naive) or primed (memory/preactivated) T-cells in vivo or in vitro, in the presence of Fc receptor-bearing accessory cells. The activation is associated with elevated T-cell homing and migration into the small intestine within 3 hours post injection. Post-activation status of the cells is characterized as Th17 polarization (<a href=\"https://www.nature.com/articles/nature10228\">Esplugues et al. 2011</a>).</br></br>Such aberrant activation and migration into the small intestines causes neutrophil infiltration, edema, accumulation of tissue fluid in the villus tips, villus atrophy, elevated cell death and inflammation. There are no reports on the effects of such activation on other peripheral organs and the model is well accepted as a small intestinal inflammation model with components involving the Th1/Th17 type immune response. The colon remains is histopathologically unaffected and does not bear any signs of elevated T-cell homing. The seeming lack of any colonic inflammation prompts to a specific inflammatory reaction restricted to the small intestine.</br></br>In this experiment, samples from the jejunum of the mice are taken at 0h, 6h, and 24h after the administration of the anti-CD3 antibody.",
  "AntiCD324h" = "The anti-CD3 enteritis model (<b>AntiCD3</b>) is a murine model generated by the administration of a monoclonal <a href=\"https://www.bdbiosciences.com/en-eu/products/reagents/flow-cytometry-reagents/research-reagents/single-color-antibodies-ruo/purified-na-le-hamster-anti-mouse-cd3e.553057?tab=product_details\">anti CD3e antibody</a>. This antibody can activate either unprimed (naive) or primed (memory/preactivated) T-cells in vivo or in vitro, in the presence of Fc receptor-bearing accessory cells. The activation is associated with elevated T-cell homing and migration into the small intestine within 3 hours post injection. Post-activation status of the cells is characterized as Th17 polarization (<a href=\"https://www.nature.com/articles/nature10228\">Esplugues et al. 2011</a>).</br></br>Such aberrant activation and migration into the small intestines causes neutrophil infiltration, edema, accumulation of tissue fluid in the villus tips, villus atrophy, elevated cell death and inflammation. There are no reports on the effects of such activation on other peripheral organs and the model is well accepted as a small intestinal inflammation model with components involving the Th1/Th17 type immune response. The colon remains is histopathologically unaffected and does not bear any signs of elevated T-cell homing. The seeming lack of any colonic inflammation prompts to a specific inflammatory reaction restricted to the small intestine.</br></br>In this experiment, samples from the jejunum of the mice are taken at 0h, 6h, and 24h after the administration of the anti-CD3 antibody.",
  "Opa1KO" = "<b>OPA1</b> is a dynamin-related mitochondrial GTPase which is required for the mitochondrial fusion. Fusion allows several mitochondria to form an interconnected network and control the shape and function of these organelles. To investigate the impact of impaired mitochondrial fusion and the consequence of reduced <i>Opa1</i> expression in the intestinal epithelium, mice carrying loxP-flanked <i>Opa1</i> alleles (<i>Opa1<sup>fl/fl</sup></i>) were crossed with B6.Cg-Tg(Vil1-cre/ERT2)23Syr/J (Villin-CreERT2) transgenic mice, resulting in mice (<b>Opa1<sup>ΔIEC</sup></b>), in which <i>Opa1</i> could be deleted specifically in the intestinal epithelium at any time by injection of tamoxifen (<a href=\"https://www.science.org/doi/10.1126/scitranslmed.adn8699?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed\"> Bao et al. 2025</a>).</br></br>Within two weeks of <i>Opa1</i> deletion, Opa1<sup>ΔIEC</sup> mice began to show significant weight loss. High-resolution endoscopic imaging revealed signs of colitis in these mice, including thickening of the bowel wall, increased granularity, mucosal erosions and colonic mucosal bleeding. In addition, histological analysis showed clear destruction of the gut structure and severe inflammation in the ileum, cecum, and colon of <i>Opa1<sup>ΔIEC</sup></i> mice, along with the upregulation of inflammatory mediators."
  # "DSSTCim" = "3% DSS, Day 3. The DSS colitis model is based on the administration of the sulfated polysaccharide DSS to mice orally in drinking water. This compound induces severe colitis after a few days, with symptoms such as bloody diarrhea, weight loss, epithelial damage that can originate ulcers and immune cell infiltration, resembling symptoms observed in flares of ulcerative colitis in humans. Because of these injuries, the epithelial barrier becomes compromised, and the cells of the sub epithelial layer of the gut are exposed to the antigens present in the intestinal lumen, such as bacteria and other commensal microbiota, developing an inflammatory response.</br>Because of the models simplicity and reproducibility, we can modify the doses of DSS and treatment cycles in order to generate forms of acute and chronic intestinal inflammation, as well as use the model for the study of the regeneration and recovery of the intestinal epithelium. </br>In this database, the experiments included that are based in this model are the Acute and Chronic DSS colitis, and an acute DSS time course study, that samples mice over multiple time points, following the trancriptome as the inflammation develops, and then the mouse recovers from it (https://www.nature.com/articles/nprot.2017.044).",
  # "DSSTCih" = "3% DSS, Day 7. The DSS colitis model is based on the administration of the sulfated polysaccharide DSS to mice orally in drinking water. This compound induces severe colitis after a few days, with symptoms such as bloody diarrhea, weight loss, epithelial damage that can originate ulcers and immune cell infiltration, resembling symptoms observed in flares of ulcerative colitis in humans. Because of these injuries, the epithelial barrier becomes compromised, and the cells of the sub epithelial layer of the gut are exposed to the antigens present in the intestinal lumen, such as bacteria and other commensal microbiota, developing an inflammatory response.</br>Because of the models simplicity and reproducibility, we can modify the doses of DSS and treatment cycles in order to generate forms of acute and chronic intestinal inflammation, as well as use the model for the study of the regeneration and recovery of the intestinal epithelium. </br>In this database, the experiments included that are based in this model are the Acute and Chronic DSS colitis, and an acute DSS time course study, that samples mice over multiple time points, following the trancriptome as the inflammation develops, and then the mouse recovers from it (https://www.nature.com/articles/nprot.2017.044).",
  # "DSSTCrm" = "3% DSS, Day 12. The DSS colitis model is based on the administration of the sulfated polysaccharide DSS to mice orally in drinking water. This compound induces severe colitis after a few days, with symptoms such as bloody diarrhea, weight loss, epithelial damage that can originate ulcers and immune cell infiltration, resembling symptoms observed in flares of ulcerative colitis in humans. Because of these injuries, the epithelial barrier becomes compromised, and the cells of the sub epithelial layer of the gut are exposed to the antigens present in the intestinal lumen, such as bacteria and other commensal microbiota, developing an inflammatory response.</br>Because of the models simplicity and reproducibility, we can modify the doses of DSS and treatment cycles in order to generate forms of acute and chronic intestinal inflammation, as well as use the model for the study of the regeneration and recovery of the intestinal epithelium. </br>In this database, the experiments included that are based in this model are the Acute and Chronic DSS colitis, and an acute DSS time course study, that samples mice over multiple time points, following the trancriptome as the inflammation develops, and then the mouse recovers from it (https://www.nature.com/articles/nprot.2017.044).",
  # "DSSTCrf" = "3% DSS, Day 19. The DSS colitis model is based on the administration of the sulfated polysaccharide DSS to mice orally in drinking water. This compound induces severe colitis after a few days, with symptoms such as bloody diarrhea, weight loss, epithelial damage that can originate ulcers and immune cell infiltration, resembling symptoms observed in flares of ulcerative colitis in humans. Because of these injuries, the epithelial barrier becomes compromised, and the cells of the sub epithelial layer of the gut are exposed to the antigens present in the intestinal lumen, such as bacteria and other commensal microbiota, developing an inflammatory response.</br>Because of the models simplicity and reproducibility, we can modify the doses of DSS and treatment cycles in order to generate forms of acute and chronic intestinal inflammation, as well as use the model for the study of the regeneration and recovery of the intestinal epithelium. </br>In this database, the experiments included that are based in this model are the Acute and Chronic DSS colitis, and an acute DSS time course study, that samples mice over multiple time points, following the trancriptome as the inflammation develops, and then the mouse recovers from it (https://www.nature.com/articles/nprot.2017.044).",
  # "OxC_old" = "The haptenizing agent oxazolone causes severe colitis after intrarectal administration in mice. The mice suffer of inflammation of the distal mucosa and submucosa, and experience ulcerations in the epithelium. Multiple immune cells, such as macrophages, neutrophils and lymphocytes can be found infiltrating the lamina propria. Multiple strains of mice can be used to run this model, some of them being more susceptible than others. Strains SJL/L or C57BL/10 have more sensibility to the treatment, but other strains, such as C57BL/6 might need some form of subcutaneous sensibilization beforehand.</br>Some of the histological features that are observed in the mice, such as inflammation of the distant colon, or an elevated production of cytokines are similar to the symptoms observed in ulcerative colitis in humans, so the model has been used to study such responses in the context of the disease.</br>Finally, changes in the dosage of oxazolone can also trigger different types of immune responses, like mixed Th1/Th2. In some strains, a chronic form of colitis can be obtained performing multiple cycles of treatment with oxazolone. (https://www.nature.com/articles/nprot.2017.044).",
  # "AOMDSS_e" = "1.5% DSS, Day 9. As an extensión of the DSS inflammation model, the AOM/DSS colon cancer model uses the strain on the tissue of the multiple DSS colitis cycles to create an environment where a carcinogenic agent can generate tumors most effectively.</br>AOM (Methyl-methylimino-oxidoazanium) is a procarcinogen that is metabolized by cytochrome p450 into methylazocymethanol (MAM), a highly alkylating compound that induces G to A transitions in genetic material. This methabolized compound is excreted into the bile, and absorbed by the intestinal epithelium, where it starts inducing mutations, so its effect in the already damaged tissue of a mouse with chronic inflammation induced by cycles of DSS is greatly enhanced.</br>Some of the key features of this model consist in how relatively quick and accurately it is able to model colitis associated cancer, as tumors develop at around 10 weeks. The histopatology of the induced tumors also replicates multiple facets of human colitis induced cancer, so it has been widely used to study the development and pathogenesis of infllamatory colorectal cancer. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5035391/)",
  # "AOMDSS_l" = "1% DSS, Day 55. As an extensión of the DSS inflammation model, the AOM/DSS colon cancer model uses the strain on the tissue of the multiple DSS colitis cycles to create an environment where a carcinogenic agent can generate tumors most effectively.</br>AOM (Methyl-methylimino-oxidoazanium) is a procarcinogen that is metabolized by cytochrome p450 into methylazocymethanol (MAM), a highly alkylating compound that induces G to A transitions in genetic material. This methabolized compound is excreted into the bile, and absorbed by the intestinal epithelium, where it starts inducing mutations, so its effect in the already damaged tissue of a mouse with chronic inflammation induced by cycles of DSS is greatly enhanced.</br>Some of the key features of this model consist in how relatively quick and accurately it is able to model colitis associated cancer, as tumors develop at around 10 weeks. The histopatology of the induced tumors also replicates multiple facets of human colitis induced cancer, so it has been widely used to study the development and pathogenesis of infllamatory colorectal cancer. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5035391/)",
  # "AOMDSS_t" = "1% DSS + AOM. Day 59-63. As an extensión of the DSS inflammation model, the AOM/DSS colon cancer model uses the strain on the tissue of the multiple DSS colitis cycles to create an environment where a carcinogenic agent can generate tumors most effectively.</br>AOM (Methyl-methylimino-oxidoazanium) is a procarcinogen that is metabolized by cytochrome p450 into methylazocymethanol (MAM), a highly alkylating compound that induces G to A transitions in genetic material. This methabolized compound is excreted into the bile, and absorbed by the intestinal epithelium, where it starts inducing mutations, so its effect in the already damaged tissue of a mouse with chronic inflammation induced by cycles of DSS is greatly enhanced.</br>Some of the key features of this model consist in how relatively quick and accurately it is able to model colitis associated cancer, as tumors develop at around 10 weeks. The histopatology of the induced tumors also replicates multiple facets of human colitis induced cancer, so it has been widely used to study the development and pathogenesis of infllamatory colorectal cancer. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5035391/)",
  # "WH6" = "Hour 6 after wound. The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 6 since the infliction of the wound.",
  # "WH24" = "Hour 24 after wound. The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 24 since the infliction of the wound.",
  # "WH48" = "Hour 48 after wound. The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 48 since the infliction of the wound.",
  #"HhInf" = "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn. Zhro li'hee, kadishtu naflmnahn' bug fhtagn ch' f''fhalma, Nyarlathotep grah'n athg Azathoth 'bthnk n'ghft. "
)

#' @export
markerNames <- list(
  "Dystal enterocytes" = "markers_EnterocyteDist",
  "Proximal enterocytes" = "markers_EnterocyteProx",
  "Enteroendocrine cells" = "markers_Enteroendocrine",
  "Goblet cells" = "markers_Goblet",
  "M cells" = "markers_Mcells",
  "Paneth cells" = "markers_Paneth",
  "Stem cells" = "markers_Stem",
  "Transit Amplifying cells" = "markers_TAprog",
  "Tuft cells" = "markers_Tuft",
  "Fibroblasts" = "markers_Fibroblasts",
  "Monocyte derived dendritic cells" = "markers_MODC",
  "Plasma cells" = "markers_Plasma",
  "T lymphocytes" = "markers_Tcells",
  "B lymphocytes" = "markers_Bcells",
  "Mast cells" = "markers_Mast",
  "Mitochondrial genes" = "markers_Mitochondrial",
  "NK lymphocytes" = "markers_NK",
  "Endothelial cells" = "markers_Endothelial",
  "Neutrophils" = "markers_Neutrophils",
  "Smooth muscle" = "markers_SmoothMuscle",
  "Enteric glial cells" = "markers_EntericGlia",
  "Enteric neurons" = "markers_EntericNeuron"
)

#' @export
imgLabels <- list(
  'logo1' = "www/logo1.png"
)

#' @export
contactDesc <- "</br><b>Lead developer:</b></br>\tMiguel Gonzalez Acera</br>\tMiguel.GonzalezAcera@uk-erlangen.de</br></br><b>Project chief:</b></br>\tChristoph Becker</br>\tChristoph.becker@uk-erlangen.de</br></br><b>\tIMPORTANT</b>: As the tool is constantly being developed, some errors and bugs are expected as new features are added. If a bug or a mistake is found when consulting the information hosted, please contact us and communicate us the issue, and we will fix it as soon as possible.</br></br><b>Cite us:</b></br>Miguel Gonzalez Acera, Jay V. Patankar, Lena Erkert, Roodline Cineus, Reyes Gámez-Belmonte, Tamara Leupold, Marvin Bubeck, Li-Li Bao, Martin Dinkel, Ru Wang, Heidi Limberger, Iris Stolzer, Katharina Gerlach, Fabrizio Mascia, Kristina Koop, Christina Plattner, Gregor Sturm, Benno Weigmann, Claudia Günther, Stefan Wirtz, Kai Hildner, Anja A. Kühl, Britta Siegmund, Raja Atreya, The IBDome Consortium, Ahmed N. Hegazy, Zlatko Trajanoski, Markus F. Neurath, and Christoph Becker. \"Integrated Multi-Model Analysis of Intestinal Inflammation Exposes Key Molecular Features of Preclinical and Clinical IBD\" bioRxiv, August 20, 2024. (<a href=\"https://doi.org/10.1101/2024.08.14.607902.\">DOI</a>)"