box::use(
  utils[...],
  RMariaDB[...]
)


# Ask database for the usernames and passwords for the tool
userQuery <- function(){
  # Establish the connection to the projects database
  usersDb <- dbConnect(RMariaDB::MariaDB(), user='sepia', password="sepia_TRR241", dbname='Users', host='localhost')
  
  # Create the query with the project name
  queryUserText <- "select * from SepiaUsers;"
  
  # Run the query against the database and fetch the resulting dataframe
  rsUserInsert <- dbSendQuery(usersDb, queryUserText)
  dbUserRows <- dbFetch(rsUserInsert)
  
  # Clear the query
  dbClearResult(rsUserInsert)
  
  # Disconnect the database
  dbDisconnect(usersDb)
  
  # return projects dataframe
  return(dbUserRows)
}

#Temporal table for usernames and passwords
#' @export
userBase <- userQuery()

# Generate lists of options for the displays
#' @export
fullExp <- list(
  "DSSTC" = "DSS_TimeCourse",
  "WH" = "WoundHealing"
)

#' @export
singleExp <- list(
  "AcDSS" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_DSS_Cerl"),
  "cDSS" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_cDSS_Cerl"),
  "DSSTCim" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Inf_mid_Healthy"),
  "DSSTCih" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Inf_hi_Healthy"),
  "DSSTCrm" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Rec_mod_Healthy"),
  "DSSTCrf" = list("project" = "DSS_TimeCourse", "tabid" = "DSS_TimeCourse_Rec_ful_Healthy"),
  "OxC" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_OxC_Cerl"),
  "TC" = list("project" = "MouseModelsInflammation", "tabid" = "MouseModelsInflammation_TC_RKO"),
  "TdAc" = list("project" = "TNFdARE_model", "tabid" = "TNFdARE_model_Col_dARE_Col_WT"),
  "TdAi" = list("project" = "TNFdARE_model", "tabid" = "TNFdARE_model_SI_dARE_SI_WT"),
  "AcTNBS" = list("project" = "TNBS_model", "tabid" = "TNBS_model_TNBS_Ac_Healthy"),
  "cTNBS" = list("project" = "TNBS_model", "tabid" = "TNBS_model_TNBS_Chr_Healthy"),
  "C8KOc" = list("project" = "Casp8Colon", "tabid" = "Casp8Colon_Col_Casp8dIEC_Col_Casp8flox"),
  "C8KOi" = list("project" = "Casp8Ileum", "tabid" = "Casp8Ileum_D4_Casp8dIEC_D4_Casp8flox"),
  "AOMDSS_e" = list("project" = "AOMDSS", "tabid" = "AOMDSS_AcDSS_Healthy"),
  "AOMDSS_l" = list("project" = "AOMDSS", "tabid" = "AOMDSS_chrDSS_Healthy"),
  "AOMDSS_t" = list("project" = "AOMDSS", "tabid" = "AOMDSS_AOMDSS_Healthy"),
  "WH6" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h6_h0"),
  "WH24" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h24_h0"),
  "WH48" = list("project" = "WoundHealing", "tabid" = "WoundHealing_h48_h0"),
  "EvInf" = list("project" = "Eimeria_vermiformis_model", "tabid" = "Eimeria_vermiformis_model_EV_WT"),
  "HhInf" = list("project" = "HhColitis", "tabid" = "HhColitis_HhCol_SSt")
)

#' @export
displayNames <- list("Acute DSS" = "AcDSS",
                     "Chronic DSS" = "cDSS",
                     "DSS Time course - Mid inflammation" = "DSSTCim",
                     "DSS Time course - High inflammation" = "DSSTCih",
                     "DSS Time course - Moderate recovery" = "DSSTCrm",
                     "DSS Time course - Full recovery" = "DSSTCrf",
                     "Oxazolone colitis" = "OxC",
                     "T cell transfer colitis" = "TC",
                     "TNF-dARE colitis" = "TdAc",
                     "TNF-dARE ileitis" = "TdAi",
                     "Acute TNBS colitis" = "AcTNBS",
                     "Chronic TNBS colitis" = "cTNBS",
                     "Casp8 KO colitis" = "C8KOc",
                     "Casp8 KO ileitis" = "C8KOi",
                     "AOM DSS - early" = "AOMDSS_e",
                     "AOM DSS - late" = "AOMDSS_l",
                     "AOM DSS - tumor" = "AOMDSS_t",
                     "Wound Healing time course - h6" = "WH6",
                     "Wound Healing time course - h24" = "WH24",
                     "Wound Healing time course - h48" = "WH48",
                     "Eimeria vermiformis infection" = "EvInf",
                     "Helicobacter colitis infection" = "HhInf"
                     )

#' @export
modelDescriptions <- list(
  "AcDSS" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "cDSS" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "DSSTCim" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "DSSTCih" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "DSSTCrm" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "DSSTCrf" = "Oral administration of the sulfated polysaccharide DSS to mice via drinking water induces severe colitis characterized by weight loss, bloody diarrhea, ulcer formation, loss of epithelial cells and infiltrations with neutrophils, resembling some features of flares in human UC. Although the exact mechanism of its colitogenicity remains incompletely understood, it is believed that DSS exerts toxicity toward intestinal epithelial cells of the basal crypts. Recent findings suggest that DSS associates with colonic medium-chain-length fatty acids abundantly present in the chow and that these complexes are absorbed and metabolized by epithelial cells. Upon epithelial injury, compromised barrier integrity subsequently exposes mucosal and submucosal immune cells to luminal antigens (e.g., bacterial antigens), resulting in a rapid and profound inflammatory immune response. On the basis of its simplicity and reproducibility, the modification of doses and treatment cycles allows modeling of acute, relapsing and chronic forms of intestinal inflammation, as well as analysis of repeated tissue regeneration and chronic wound healing upon epithelial injury. For instance, repeated epithelial damage and wound repair phases induced by the administration of DSS for several cycles may (dependent on the mouse strain used) cause a non-self-limiting chronic form of colitis (https://www.nature.com/articles/nprot.2017.044).",
  "OxC" = "Oxazolone is a hapten reagent that prompts severe colitis after intrarectal administration in mice. The acute inflammation of the distal colonic mucosa and submucosa is characterized by ulcerations and lamina propria infiltrations of neutrophils, macrophages and lymphocytes. Although SJL/J and C57BL/10 mice are highly susceptible strains, C57BL/6 mice are more resistant to oxazolone colitis and may require a subcutaneous sensitization step before intrarectal challenge. Histological features (e.g., epithelial damage and infiltration of neutrophils, macrophages and lymphocytes in mucosa and submucosa), preferential inflammation of the distal colon and an elevated production of type 2 and type 9 cytokines (interleukin (IL)-4, IL-5, IL-9 and IL-13) by lamina propria T cells are similar to the characteristics of UC that have been observed in humans. Natural killer T cells secreting IL-13 have been identified as an important trigger of disease, presumably after activation by antigen presentation via CD1d19. Moreover, IL-4R signaling to T cells and B cells and IL-9 production by T cells have been demonstrated to contribute to the disease. Thus, this model has been used to study the type-2- and type-9-related immune responses during intestinal inflammation. Importantly, lower doses of oxazolone may also induce a mixed Th1/Th2 response, highlighting that oxazolone colitis requires individual optimization strategies in each mouse strain. In Balb/c mice, chronic colitis can be induced by repetitive administration of oxazolone. This model may be particularly useful in the study of some specific features of the inflammatory response seen in chronic IBDs (https://www.nature.com/articles/nprot.2017.044).",
  "TC" = "One mouse model that is extremely suited to studying CD4 + T cell-based pathogenesis is the adoptive transfer model of colitis. This model works on two important concepts that have been well established.</br><ol type=”1><li>T cells that express high CD45RB (mainly naïve T cells) from the spleen or lymph nodes possess T cells capable of trafficking to the intestine and causing severe intestinal disease.</li><li>The effect of regulatory T cells (contained in CD45RB lo cells) can overcome the effect of the above mentioned CD4+ effector T cells.</li></ol></br>Briefly, the method originally described by Powrie involves adoptive transfer of naïve T cells (CD4+ CD45RBhigh) into immune-deficient Rag KO mice. These naïve T cells react in a severe fashion on experiencing the gut antigens, become activated forming colitogenic T cells secreting cytokines that causing severe gut inflammation involving both small and large intestines. It usually takes around 6-8 weeks, depending on the microbial populations present in the animal facility, to develop severe disease manifested by hunching, progressive weight loss, and diarrhea. Histopathology reveals transmural inflammation, dense infiltrates involving neutrophils, and crypt abscessation. (https://pubmed.ncbi.nlm.nih.gov/22262449/)",
  "TdAc" = "These mice have a deletion in the TNF AU-rich elements (ARE), which are responsible for TNF-mRNA destabilization and translational repression. 18 As a consequence, they exhibit markedly increased TNF-serum levels and develop a specific human CD-like phenotype characterized by inflammations primarily localized to the terminal ileum and occasionally to the proximal colon. Heterozygous TNFARE mice (TNFARE/) at 4 months of age displayed severe inflammation in the ileum illustrated by mucosal and submucosal infiltration of chronic and acute inflammatory cells. 19 No prominent signs of diarrhea were observed. Furthermore, these mice show features of arthritis.",
  "TdAi" = "These mice have a deletion in the TNF AU-rich elements (ARE), which are responsible for TNF-mRNA destabilization and translational repression. 18 As a consequence, they exhibit markedly increased TNF-serum levels and develop a specific human CD-like phenotype characterized by inflammations primarily localized to the terminal ileum and occasionally to the proximal colon. Heterozygous TNFARE mice (TNFARE/) at 4 months of age displayed severe inflammation in the ileum illustrated by mucosal and submucosal infiltration of chronic and acute inflammatory cells. 19 No prominent signs of diarrhea were observed. Furthermore, these mice show features of arthritis.",
  "AcTNBS" = "In this model, colonic inflammation is induced in susceptible strains of mice by intrarectal administration of the haptenating substance TNBS together with ethanol. Ethanol is essential to providing access to intestinal epithelial cells, impairing barrier function and allowing TNBS to penetrate the bowel wall. TNBS administration is believed to result in haptenization of colonic or microbiota-derived proteins and subsequently in the generation of TNP-specific CD4+ T cells and antibodies. As this model is associated with the increased presence of highly activated T cells and as such T cells have a key pathogenic role in TNBS colitis, this model is suitable to ascertaining CD4+ T-cell-dependent immunity in the inflamed gut. Innate immune mechanisms are also involved in the development of TNBS colitis, as TNBS-dependent signs of acute mucosal inflammation can also be initiated in lymphopenic mice. The intensity and the length of the inflammatory process are critically dependent on several factors such as the genetic background of the mice and the presence or absence of T-cell-activating bacterial strains in the local animal facility. An individual optimization of TNBS administration in each mouse strain and in each facility is therefore essential. Depending on the microflora and the background strains used, different cytokine profiles have been described, including activation of Th1, Th2 and Th17 cytokines. Histologically, transmural inflammation with infiltrates of macrophages, neutrophils and lymphocytes, as well as colonic patch hypertrophy, has been described. As some of the immunological and histopathological characteristics resemble features of CD, TNBS colitis has been broadly used to study a variety of aspects potentially relevant to this disease.</br>CD is frequently complicated by the gradual development of tissue fibrosis and stenosis induced by the activation of mesenchymal cells via multiple mediators released in the context of chronic inflammation. Interestingly, chronic TNBS colitis in BALB/c mice is characterized by persistent lamina propria fibrosis, indicating that this model is a useful tool for studying the potential pathological mechanisms underlying the intestinal fibrosis that accompanies human IBDs (https://www.nature.com/articles/nprot.2017.044).",
  "cTNBS" = "In this model, colonic inflammation is induced in susceptible strains of mice by intrarectal administration of the haptenating substance TNBS together with ethanol. Ethanol is essential to providing access to intestinal epithelial cells, impairing barrier function and allowing TNBS to penetrate the bowel wall. TNBS administration is believed to result in haptenization of colonic or microbiota-derived proteins and subsequently in the generation of TNP-specific CD4+ T cells and antibodies. As this model is associated with the increased presence of highly activated T cells and as such T cells have a key pathogenic role in TNBS colitis, this model is suitable to ascertaining CD4+ T-cell-dependent immunity in the inflamed gut. Innate immune mechanisms are also involved in the development of TNBS colitis, as TNBS-dependent signs of acute mucosal inflammation can also be initiated in lymphopenic mice. The intensity and the length of the inflammatory process are critically dependent on several factors such as the genetic background of the mice and the presence or absence of T-cell-activating bacterial strains in the local animal facility. An individual optimization of TNBS administration in each mouse strain and in each facility is therefore essential. Depending on the microflora and the background strains used, different cytokine profiles have been described, including activation of Th1, Th2 and Th17 cytokines. Histologically, transmural inflammation with infiltrates of macrophages, neutrophils and lymphocytes, as well as colonic patch hypertrophy, has been described. As some of the immunological and histopathological characteristics resemble features of CD, TNBS colitis has been broadly used to study a variety of aspects potentially relevant to this disease.</br>CD is frequently complicated by the gradual development of tissue fibrosis and stenosis induced by the activation of mesenchymal cells via multiple mediators released in the context of chronic inflammation. Interestingly, chronic TNBS colitis in BALB/c mice is characterized by persistent lamina propria fibrosis, indicating that this model is a useful tool for studying the potential pathological mechanisms underlying the intestinal fibrosis that accompanies human IBDs (https://www.nature.com/articles/nprot.2017.044).",
  "C8KOc" = "When studying the dynamics of cell death pathways, it was found when knocking out the Caspase 8 gene, that regulates the apoptosis cell death pathway, the cells in the epithelium undergo cell death using the necroptosis pathway. Mice born with this gene knocked out develop a form of ileitis when growing, as well as a form of colitis in some cases.",
  "C8KOi" = "When studying the dynamics of cell death pathways, it was found when knocking out the Caspase 8 gene, that regulates the apoptosis cell death pathway, the cells in the epithelium undergo cell death using the necroptosis pathway. Mice born with this gene knocked out develop a form of ileitis when growing, as well as a form of colitis in some cases.",
  "AOMDSS_e" = "The AOM/DSS model is a powerful, reproducible, and relatively inexpensive initiation-promotion model that utilizes chemical induction of DNA damage followed by repeated cycles of colitis.</br>AOM (Methyl-methylimino-oxidoazanium, CH3N=N(→O)CH3) is a procarcinogen that is metabolized by cytochrome p450, isoform CYP2E1, converting it into methylazocymethanol (MAM), a highly reactive alkylating species that induces O6 methylguanine adducts in DNA resulting in G→A transitions. After excretion into the bile, it is taken up by colonic epithelium and induces mutagenesis. DSS is a heparin-like polysaccharide that is dissolved in the drinking water and inflicts colonic epithelial damage, inducing colitis mimicking some of the features of IBD. Combining AOM and DSS provides a two-step tumor model of CAC.</br>Key features of the AOM/DSS model include its relatively short timeline and accurate modeling of CAC. Tumor development can occur in as short as 10 weeks. Moreover, the histopathology of AOM/DSS-induced tumors recapitulates key facets of human CAC such as distally-located tumors and invasive adenocarcinomas. Application of the AOM/DSS model has been critical in unraveling the pathogenesis of CAC: from the role of signaling pathways (e.g. Toll-like receptor 4, IKKβ, and IL-6) and antioxidant machinery (e.g. glutathione peroxidase) to the influence of the microbiota and transcriptional corepressors (e.g. Myeloid translocation genes). Thus, the AOM/DSS model is a powerful platform to employ when studying the pathogenesis of inflammatory colorectal cancer.",
  "AOMDSS_l" = "The AOM/DSS model is a powerful, reproducible, and relatively inexpensive initiation-promotion model that utilizes chemical induction of DNA damage followed by repeated cycles of colitis.</br>AOM (Methyl-methylimino-oxidoazanium, CH3N=N(→O)CH3) is a procarcinogen that is metabolized by cytochrome p450, isoform CYP2E1, converting it into methylazocymethanol (MAM), a highly reactive alkylating species that induces O6 methylguanine adducts in DNA resulting in G→A transitions. After excretion into the bile, it is taken up by colonic epithelium and induces mutagenesis. DSS is a heparin-like polysaccharide that is dissolved in the drinking water and inflicts colonic epithelial damage, inducing colitis mimicking some of the features of IBD. Combining AOM and DSS provides a two-step tumor model of CAC.</br>Key features of the AOM/DSS model include its relatively short timeline and accurate modeling of CAC. Tumor development can occur in as short as 10 weeks. Moreover, the histopathology of AOM/DSS-induced tumors recapitulates key facets of human CAC such as distally-located tumors and invasive adenocarcinomas. Application of the AOM/DSS model has been critical in unraveling the pathogenesis of CAC: from the role of signaling pathways (e.g. Toll-like receptor 4, IKKβ, and IL-6) and antioxidant machinery (e.g. glutathione peroxidase) to the influence of the microbiota and transcriptional corepressors (e.g. Myeloid translocation genes). Thus, the AOM/DSS model is a powerful platform to employ when studying the pathogenesis of inflammatory colorectal cancer.",
  "AOMDSS_t" = "The AOM/DSS model is a powerful, reproducible, and relatively inexpensive initiation-promotion model that utilizes chemical induction of DNA damage followed by repeated cycles of colitis.</br>AOM (Methyl-methylimino-oxidoazanium, CH3N=N(→O)CH3) is a procarcinogen that is metabolized by cytochrome p450, isoform CYP2E1, converting it into methylazocymethanol (MAM), a highly reactive alkylating species that induces O6 methylguanine adducts in DNA resulting in G→A transitions. After excretion into the bile, it is taken up by colonic epithelium and induces mutagenesis. DSS is a heparin-like polysaccharide that is dissolved in the drinking water and inflicts colonic epithelial damage, inducing colitis mimicking some of the features of IBD. Combining AOM and DSS provides a two-step tumor model of CAC.</br>Key features of the AOM/DSS model include its relatively short timeline and accurate modeling of CAC. Tumor development can occur in as short as 10 weeks. Moreover, the histopathology of AOM/DSS-induced tumors recapitulates key facets of human CAC such as distally-located tumors and invasive adenocarcinomas. Application of the AOM/DSS model has been critical in unraveling the pathogenesis of CAC: from the role of signaling pathways (e.g. Toll-like receptor 4, IKKβ, and IL-6) and antioxidant machinery (e.g. glutathione peroxidase) to the influence of the microbiota and transcriptional corepressors (e.g. Myeloid translocation genes). Thus, the AOM/DSS model is a powerful platform to employ when studying the pathogenesis of inflammatory colorectal cancer.",
  "WH6" = "The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 6 since the infliction of the wound.",
  "WH24" = "The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 24 since the infliction of the wound.",
  "WH48" = "The processes of resolution play an important role in the dynamics of IBD, so, to observe the natural processes of resolution of wounds in the epithelium over the transcriptome, a small wound is made in the mouse’s colon and samples are taken at multiple points in time to observe the state of the healing. Samples are taken at Hour 48 since the infliction of the wound.",
  "EvInf" = "Eimeria vermiformis is a tissue specific, intracellular single cell protozoan, which infects the small intestinal epithelia. Unlike the related pathogen used in infection models, Toxoplasma gondii, this is a natural, self-limiting, murine parasite, which induces a strong immune response and establishes long-lasting protection against subsequent infections. Furthermore, E. vermiformis is monoxenous, its life cycle is completed without the need of a second host species. It is therefore an ideal pathogen to study the mechanisms of host protection against primary and secondary infection at the small intestinal barrier.</br>Mice infected with E. vermiformis excrete a non-infectious, unsporulated form of oocysts into the environment. Once in contact with oxygen and moisture, in a process which takes between 2 to 7 days, these oocysts mature into an infectious, sporulated form, which, upon ingestion, disseminates the infection to other animals.</br>The E. vermiformis infection model has been used in the past and has yielded valuable information in areas such as the role of αβ and γδ T cells that line the small intestinal epithelia and the influence of age of the host in the development of protective immune responses in the intestine. More recently we have used the E. vermiformis model to highlight the role of mitochondria in controlling the activation state of epithelial-resident T lymphocytes. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6485400/)",
  "HhInf" = "Pioneering work in the 1990s first linked a novel microaerobic bacterium, Helicobacter hepaticus, with chronic active hepatitis and inflammatory bowel disease in several murine models. Targeted H. hepaticus infection experiments subsequently demonstrated its ability to induce colitis, colorectal cancer, and extraintestinal diseases in a number of mouse strains with defects in immune function and/or regulation. H. hepaticus is now widely utilized as a model system to dissect how intestinal microbiota interact with the host to produce both inflammatory and tolerogenic responses. This model has been used to make important advances in understanding factors that regulate both acquired and innate immune response within the intestine. Further, it has been an effective tool to help define the function of regulatory T cells, including their ability to directly inhibit the innate inflammatory response to gut microbiota (https://www.nature.com/articles/mi201061#Sec12)"
  #"HhInf" = "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn. Zhro li'hee, kadishtu naflmnahn' bug fhtagn ch' f''fhalma, Nyarlathotep grah'n athg Azathoth 'bthnk n'ghft. "
)

#' @export
markerNames <- list(
  "Dystal enterocytes" = "markers_EnterocyteDist",
  "Proximal enterocytes" = "markers_EnterocyteProx",
  "Enteroendocrine cells" = "markers_Enteroendocrine",
  "Goblet cells" = "markers_Goblet",
  "M cells" = "markers_Mcells",
  "Paneth cells" = "markers_Paneth",
  "Stem cells" = "markers_Stem",
  "Transit Amplifying cells" = "markers_TAprog",
  "Tuft cells" = "markers_Tuft",
  "Fibroblasts" = "markers_Fibroblasts",
  "Monocyte derived dendritic cells" = "markers_MODC",
  "Plasma cells" = "markers_Plasma",
  "T lymphocytes" = "markers_Tcells",
  "B lymphocytes" = "markers_Bcells",
  "Mast cells" = "markers_Mast",
  "Mitochondrial genes" = "markers_Mitochondrial",
  "NK lymphocytes" = "markers_NK",
  "Endothelial cells" = "markers_Endothelial",
  "Neutrophils" = "markers_Neutrophils",
  "Smooth muscle" = "markers_SmoothMuscle",
  "Enteric glial cells" = "markers_EntericGlia",
  "Enteric neurons" = "markers_EntericNeuron"
)

#' @export
imgLabels <- list(
  'logo1' = "www/logo1.png"
)